#!/bin/sh

export XILINX_VITIS=/usr/local/xilinx_vitis
export TCLLIBPATH=/usr/local/xilinx_vitis
export TCL_LIBRARY=/usr/local/lib/tcl8.5
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib

/usr/local/bin/hw_server &
/usr/local/bin/xvc_server &
